Change by Codex: fix LocalFileSystemStorageService bean creation
Remove constructor ambiguity for LocalFileSystemStorageService and provide an ApplicationHome bean so Spring can autowire and instantiate the service.

Prompt: please fix the following error:

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'localFileSystemStorageService' defined in file [C:\Users\Kevin\deep-dive\java\projects\capstone\server\build\classes\java\main\edu\cnm\deepdive\seesomethingabq\service\storage\LocalFileSystemStorageService.class]: Failed to instantiate [edu.cnm.deepdive.seesomethingabq.service.storage.LocalFileSystemStorageService]: No default constructor found
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1344) ~[spring-beans-7.0.5.jar:7.0.5]
	...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [edu.cnm.deepdive.seesomethingabq.service.storage.LocalFileSystemStorageService]: No default constructor found
	...
Caused by: java.lang.NoSuchMethodException: edu.cnm.deepdive.seesomethingabq.service.storage.LocalFileSystemStorageService.<init>()
	...